# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcatalog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="productcatalog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productcatalog",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent product (for hierarchical organization)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.productcatalog",
            ),
        ),
        migrations.AddIndex(
            model_name="productcatalog",
            index=models.Index(
                fields=["organization", "type"], name="products_ca_organiz_375488_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcatalog",
            index=models.Index(fields=["name"], name="products_ca_name_552265_idx"),
        ),
    ]
