# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("organisation_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("organisation_name", models.CharField(max_length=255)),
                ("owner_id", models.UUIDField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cloud Organisation",
                "verbose_name_plural": "Cloud Organisations",
                "db_table": "Organisations",
            },
        ),
    ]
