# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomponent",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="products.productcatalog",
            ),
        ),
        migrations.AddField(
            model_name="dependency",
            name="source_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_dependencies",
                to="assets.softwarecomponent",
            ),
        ),
        migrations.AddField(
            model_name="dependency",
            name="target_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_dependencies",
                to="assets.softwarecomponent",
            ),
        ),
        migrations.AddIndex(
            model_name="softwarecomponent",
            index=models.Index(
                fields=["data_source", "type"], name="software_co_data_so_bc5897_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwarecomponent",
            index=models.Index(
                fields=["repository", "path"], name="software_co_reposit_c2923e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponent",
            index=models.Index(
                fields=["product", "relationship_type"],
                name="product_com_product_47beea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponent",
            index=models.Index(
                fields=["component"], name="product_com_compone_b7bd57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dependency",
            index=models.Index(
                fields=["source_component"], name="assets_depe_source__746c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dependency",
            index=models.Index(
                fields=["target_component"], name="assets_depe_target__809087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dependency",
            index=models.Index(
                fields=["dependency_type"], name="assets_depe_depende_035d26_idx"
            ),
        ),
    ]
