# Generated by Django 5.2 on 2025-05-06 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("organisation_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("organisation_name", models.CharField(max_length=255)),
                ("owner_id", models.UUIDField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Organisations",
            },
        ),
    ]
