# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_data_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_sources",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="cloudresource",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloud_resources",
                to="integrations.datasource",
            ),
        ),
        migrations.AddIndex(
            model_name="gitrepository",
            index=models.Index(
                fields=["data_source", "provider"],
                name="git_reposit_data_so_0daf45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gitrepository",
            index=models.Index(
                fields=["full_name"], name="git_reposit_full_na_ed5e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["organization", "type"], name="data_source_organiz_637563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["connection_status"], name="data_source_connect_3a3be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cloudresource",
            index=models.Index(
                fields=["data_source", "type"], name="cloud_resou_data_so_98ea3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cloudresource",
            index=models.Index(
                fields=["resource_id"], name="cloud_resou_resourc_f6c25f_idx"
            ),
        ),
    ]
