# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policies", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        ("integrations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitypolicy",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_policies",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="applicable_policies",
                to="products.productcatalog",
            ),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_jobs",
                to="integrations.datasource",
            ),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="initiated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="policies",
            field=models.ManyToManyField(
                blank=True, related_name="scan_jobs", to="policies.securitypolicy"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="policies.securitypolicy",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_results",
                to="assets.softwarecomponent",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="fixed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_results",
                to="policies.securitypolicy",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_results",
                to="products.productcatalog",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_results",
                to="policies.policyrule",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="scan_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_results",
                to="policies.scanjob",
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["organization", "policy_type"],
                name="security_po_organiz_c1097a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["is_active"], name="security_po_is_acti_251197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["data_source", "status"], name="scan_job_data_so_d814f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["scan_type"], name="scan_job_scan_ty_0b439c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyrule",
            index=models.Index(
                fields=["policy", "rule_type"], name="policy_rule_policy__1b14a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyrule",
            index=models.Index(
                fields=["target_component_type"], name="policy_rule_target__7d6282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(
                fields=["component", "status"], name="compliance__compone_f43985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(
                fields=["policy"], name="compliance__policy__3ada33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(
                fields=["scan_job"], name="compliance__scan_jo_44de6f_idx"
            ),
        ),
    ]
