# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("imports", "Code Import"),
                            ("requires", "Requires/Depends On"),
                            ("calls", "API Call"),
                            ("consumes", "Consumes Service"),
                            ("uses", "Uses Resource"),
                            ("generates", "Generates"),
                            ("deploys", "Deploys"),
                            ("connects", "Connects To"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "is_direct",
                    models.BooleanField(
                        default=True, help_text="Whether this is a direct dependency"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the dependency",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dependency",
                "verbose_name_plural": "Dependencies",
                "db_table": "assets_dependency",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Component"),
                            ("dependency", "Dependency"),
                            ("included", "Included Component"),
                            ("generated", "Generated Component"),
                            ("deployed", "Deployed Resource"),
                            ("consumed", "Consumed Service"),
                        ],
                        default="included",
                        max_length=50,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        default="medium",
                        help_text="Importance of this component to the product",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Component",
                "verbose_name_plural": "Product Components",
                "db_table": "product_component",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("code", "Source Code"),
                            ("library", "Library/Package"),
                            ("service", "Microservice"),
                            ("api", "API Component"),
                            ("database", "Database"),
                            ("function", "Serverless Function"),
                            ("infra", "Infrastructure Code"),
                            ("container", "Container"),
                            ("ai_model", "AI Model"),
                            ("config", "Configuration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Path to the component within its source",
                        max_length=1024,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "discovery_method",
                    models.CharField(
                        choices=[
                            ("automated", "Automated Scanning"),
                            ("manual", "Manual Entry"),
                            ("imported", "Imported"),
                        ],
                        default="automated",
                        max_length=50,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("version", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated_in_source", models.DateTimeField(blank=True, null=True)),
                ("security_score", models.FloatField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Software Component",
                "verbose_name_plural": "Software Components",
                "db_table": "software_component",
                "ordering": ["-created_at"],
            },
        ),
    ]
