# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwarecomponent",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discovered_components",
                to="integrations.datasource",
            ),
        ),
        migrations.AddField(
            model_name="softwarecomponent",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="integrations.gitrepository",
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="assets.softwarecomponent",
            ),
        ),
    ]
