# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("app", "Application"),
                            ("web", "Web Service"),
                            ("api", "API Service"),
                            ("infrastructure", "Infrastructure"),
                            ("data", "Data Service"),
                            ("ai", "AI Model/Service"),
                        ],
                        default="app",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("in_development", "In Development"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization and filtering",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="medium",
                        help_text="Risk level of the product",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the product",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is a business-critical product",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Catalog",
                "verbose_name_plural": "Product Catalogs",
                "db_table": "products_catalog",
                "ordering": ["-created_at"],
            },
        ),
    ]
