# Generated by Django 4.1.7 on 2025-05-07 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
        ("insights", "0001_initial"),
        ("users", "0001_initial"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgegraph",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_knowledge_graphs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgegraph",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.organization"
            ),
        ),
        migrations.AddField(
            model_name="knowledgegraph",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productcatalog",
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="cloud_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insights",
                to="integrations.cloudresource",
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                to="assets.softwarecomponent",
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                to="products.productcatalog",
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insights",
                to="integrations.gitrepository",
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="cloud_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalies",
                to="integrations.cloudresource",
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="assets.softwarecomponent",
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_anomalies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalies",
                to="products.productcatalog",
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalies",
                to="integrations.gitrepository",
            ),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.softwarecomponent",
            ),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_responses",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productcatalog",
            ),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraph",
            index=models.Index(
                fields=["organization", "graph_type"],
                name="knowledge_g_organiz_d182cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraph",
            index=models.Index(
                fields=["product"], name="knowledge_g_product_44e2fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["organization", "type"], name="insight_organiz_e4b11c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["product", "status"], name="insight_product_8d2da7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(fields=["component"], name="insight_compone_9b8465_idx"),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(
                fields=["component", "anomaly_type"],
                name="anomaly_det_compone_f6f891_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(
                fields=["product", "severity"], name="anomaly_det_product_de06eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(
                fields=["detected_at"], name="anomaly_det_detecte_993bd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["user", "created_at"], name="ai_response_user_id_baa90b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["organization"], name="ai_response_organiz_7b325f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["conversation_id"], name="ai_response_convers_12c5df_idx"
            ),
        ),
    ]
